version: "1.0"
services:
  main:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /code/
    command: python src/app.py
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: main:5000
      SERVERNAME: ${hostname}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
