version: "1.0"
services:
  main:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /home/arsen/dev/ks-tha/
        target: /code/
<<<<<<< HEAD
    command: python src/change_webhook.py
=======
    command: python src/app.py
>>>>>>> 1026da7 (notifications kinda working)
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: main:5000
      SERVERNAME: nuramatov.com
      EXTRANAMES: www.nuramatov.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
    depends_on:
      - "main"
